language: node_js
node_js:
  - "14"

install:
  - npm install

script:
  - npm run lint          # Ejecuta el an치lisis est치tico del c칩digo
  - npm run test          # Ejecuta las pruebas unitarias
  - npm run coverage      # Genera un informe de cobertura
  - npm run build         # Genera el c칩digo final
